[package]
name = "invaders"
version = "0.1.0"
edition = "2021"
authors = ["Guido Eduardo <guidoeduardonsilva@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
rusty_time = "0.12.0"
